name = "PixhawkData"
uuid = "1962aac8-0cfd-4f8a-81f1-b04d323d3c20"
authors = ["Akshay Hiregoudar"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
